# Notebook 1: Data Cleaning and Feature Engineering

This notebook prepares raw daily weather data collected from the NASA POWER API.

The goal is to clean the dataset, create useful time-based features, generate climate risk indicators, and save a processed dataset for later analysis and dashboard development.

## 1. Import libraries

In [1]:
# Import the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## 2. Load the raw dataset

In [2]:
# Load the raw dataset
df = pd.read_csv("C:/Projects/15_Climate_Risk_weather_Trends/data/raw/climate_weather_raw_combined.csv")
df.head()

,date,temperature_avg,temperature_max,temperature_min,rainfall,humidity,wind_speed,solar_radiation,city,country,latitude,longitude
0,2020-01-01,27.47,33.97,23.05,0.0,59.37,3.71,17.64,Yangon,Myanmar,16.8409,96.1735
1,2020-01-02,27.69,34.70,21.93,0.0,59.48,3.02,17.51,Yangon,Myanmar,16.8409,96.1735
2,2020-01-03,27.47,34.05,22.14,0.0,58.30,2.74,17.76,Yangon,Myanmar,16.8409,96.1735
3,2020-01-04,27.49,35.18,20.60,0.0,56.99,2.32,17.82,Yangon,Myanmar,16.8409,96.1735
4,2020-01-05,27.85,35.54,21.27,0.0,56.70,2.79,17.84,Yangon,Myanmar,16.8409,96.1735

## 3. Inspect the dataset

In [ ]:

df.shape

(8768, 12)

In [10]:
print("\nColumn names:")
print(df.columns.tolist())

Column names:
['date', 'temperature_avg', 'temperature_max', 'temperature_min', 'rainfall', 'humidity', 'wind_speed', 'solar_radiation', 'city', 'country', 'latitude', 'longitude']

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8768 entries, 0 to 8767
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             8768 non-null   object
 1   temperature_avg  8768 non-null   float64
 2   temperature_max  8768 non-null   float64
 3   temperature_min  8768 non-null   float64
 4   rainfall         8768 non-null   float64
 5   humidity         8768 non-null   float64
 6   wind_speed       8768 non-null   float64
 7   solar_radiation  8768 non-null   float64
 8   city             8768 non-null   object
 9   country          8768 non-null   object
 10  latitude         8768 non-null   float64
 11  longitude        8768 non-null   float64
dtypes: float64(9), object(3)
memory usage: 822.1+ KB

In [5]:
df.describe()

,temperature_avg,temperature_max,temperature_min,rainfall,humidity,wind_speed,solar_radiation,latitude,longitude
count,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000
mean,27.265981,32.306771,23.024778,5.678112,68.716178,2.779893,17.574252,14.978775,98.040225
std,2.584349,3.464191,3.435344,13.448578,19.223559,0.967781,4.296885,8.074589,3.337233
min,17.570000,23.880000,9.780000,0.000000,16.910000,0.500000,1.470000,1.352100,96.078500
25%,26.080000,29.770000,21.717500,0.000000,53.460000,2.100000,15.287500,12.968700,96.086450
50%,27.280000,31.250000,24.170000,1.150000,75.110000,2.620000,18.040000,18.302100,96.131300
75%,28.590000,34.490000,25.440000,5.842500,85.262500,3.290000,20.480000,20.312175,98.085075
max,35.600000,43.920000,30.250000,259.030000,95.200000,8.680000,28.050000,21.958800,103.819800

In [ ]:
# Check for missing values
df.isnull().sum()

date               0
temperature_avg    0
temperature_max    0
temperature_min    0
rainfall           0
humidity           0
wind_speed         0
solar_radiation    0
city               0
country            0
latitude           0
longitude          0
dtype: int64

In [ ]:
# Expore the duplicated values
duplicate_count = df.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [ ]:
# Check the data types
df.dtypes

date                object
temperature_avg    float64
temperature_max    float64
temperature_min    float64
rainfall           float64
humidity           float64
wind_speed         float64
solar_radiation    float64
city                object
country             object
latitude           float64
longitude          float64
dtype: object

In [12]:
# Convert Date Column
df["date"] = pd.to_datetime(df["date"])
print("Minimum date:", df["date"].min())
print("Maximum date:", df["date"].max())

Minimum date: 2020-01-01 00:00:00
Maximum date: 2025-12-31 00:00:00

In [13]:
# Sort the dataset by city and date
df = df.sort_values(by=["city", "date"]).reset_index(drop=True)
df.head()

,date,temperature_avg,temperature_max,temperature_min,rainfall,humidity,wind_speed,solar_radiation,city,country,latitude,longitude
0,2020-01-01,22.56,29.21,17.90,4.79,64.14,2.21,9.34,Mandalay,Myanmar,21.9588,96.0891
1,2020-01-02,22.87,30.14,17.65,0.76,66.13,2.17,9.82,Mandalay,Myanmar,21.9588,96.0891
2,2020-01-03,21.56,26.78,17.90,9.95,75.17,2.04,9.07,Mandalay,Myanmar,21.9588,96.0891
3,2020-01-04,21.44,27.62,18.01,6.08,79.23,2.31,9.21,Mandalay,Myanmar,21.9588,96.0891
4,2020-01-05,21.10,26.91,17.26,9.39,79.46,3.25,10.89,Mandalay,Myanmar,21.9588,96.0891

In [15]:
## Check Date Range by city
date_range_by_city = df.groupby("city")["date"].agg(["min", "max","count"])
date_range_by_city

                 min        max  count
city
Mandalay  2020-01-01 2025-12-31   2192
Naypyidaw 2020-01-01 2025-12-31   2192
Singapore 2020-01-01 2025-12-31   2192
Yangon    2020-01-01 2025-12-31   2192

## Feature Engineering

In [16]:
# Create Time-Based Features
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["month_name"] = df["date"].dt.strftime("%b")
df["day"] = df["date"].dt.day
df["day_of_year"] = df["date"].dt.dayofyear
df[["date", "year", "month", "month_name", "day", "day_of_year"]].head()

        date  year  month month_name  day  day_of_year
0 2020-01-01  2020      1        Jan    1            1
1 2020-01-02  2020      1        Jan    2            2
2 2020-01-03  2020      1        Jan    3            3
3 2020-01-04  2020      1        Jan    4            4
4 2020-01-05  2020      1        Jan    5            5

In [17]:
# Create Season Feature
def assign_season(month):
    if month in [3,4,5]:
        return "Hot Season"
    elif month in [6,7,8,9,10]:
        return "Rainy Season"
    else:
        return "Cool Season"

df["season"] = df["month"].apply(assign_season)
df[['date', 'month', 'month_name', 'season']].head()

        date  month month_name       season
0 2020-01-01      1        Jan  Cool Season
1 2020-01-02      1        Jan  Cool Season
2 2020-01-03      1        Jan  Cool Season
3 2020-01-04      1        Jan  Cool Season
4 2020-01-05      1        Jan  Cool Season

In [18]:
# Create climate risk indicator columns
df["heat_risk_day"] = np.where(df["temperature_max"] >= 35,1,0)
df["very_hot_day"] = np.where(df["temperature_max"] >= 38,1,0)
df["heavy_rain_day"] = np.where(df["rainfall"] >= 50,1,0)
df["dry_day"] = np.where(df["rainfall"] < 1,1,0)

df[
    [
        "date",
        "city",
        "temperature_max",
        "rainfall",
        "heat_risk_day",
        "very_hot_day",
        "heavy_rain_day",
        "dry_day",
    ]
].head()

,date,city,temperature_max,rainfall,heat_risk_day,very_hot_day,heavy_rain_day,dry_day
0,2020-01-01,Mandalay,29.21,4.79,0,0,0,0
1,2020-01-02,Mandalay,30.14,0.76,0,0,0,1
2,2020-01-03,Mandalay,26.78,9.95,0,0,0,0
3,2020-01-04,Mandalay,27.62,6.08,0,0,0,0
4,2020-01-05,Mandalay,26.91,9.39,0,0,0,0

In [19]:
# Create Temperature Range Feature
df["temperature_range"] = df["temperature_max"] - df["temperature_min"]
df[["date", "city", "temperature_max", "temperature_min", "temperature_range"]].head()

        date      city  temperature_max  temperature_min  temperature_range
0 2020-01-01  Mandalay            29.21            17.90              11.31
1 2020-01-02  Mandalay            30.14            17.65              12.49
2 2020-01-03  Mandalay            26.78            17.90               8.88
3 2020-01-04  Mandalay            27.62            18.01               9.61
4 2020-01-05  Mandalay            26.91            17.26               9.65

In [21]:
# Create Rainfall Category
def categorize_rainfall(rainfall):
    if rainfall == 0:
        return "NO Rain"
    elif rainfall < 10:
        return "Light Rain"
    elif rainfall < 50:
        return "Moderate Rain"
    else:
        return "Heavy Rain"
df["rainfall_category"] = df["rainfall"].apply(categorize_rainfall)
df[["date", "city", "rainfall", "rainfall_category"]].head()

        date      city  rainfall rainfall_category
0 2020-01-01  Mandalay      4.79        Light Rain
1 2020-01-02  Mandalay      0.76        Light Rain
2 2020-01-03  Mandalay      9.95        Light Rain
3 2020-01-04  Mandalay      6.08        Light Rain
4 2020-01-05  Mandalay      9.39        Light Rain

In [22]:
# Create Temperature Category
def categorize_temperature(temp_max):
    if temp_max < 30:
        return "Normal"
    elif temp_max < 35:
        return "Warm"
    elif temp_max < 38:
        return "Hot"
    else:
        return "Extreme Heat"

df["temperature_category"] = df["temperature_max"].apply(categorize_temperature)
df[["date", "city", "temperature_max", "temperature_category"]].head()

        date      city  temperature_max temperature_category
0 2020-01-01  Mandalay            29.21               Normal
1 2020-01-02  Mandalay            30.14                 Warm
2 2020-01-03  Mandalay            26.78               Normal
3 2020-01-04  Mandalay            27.62               Normal
4 2020-01-05  Mandalay            26.91               Normal

In [23]:
# Create Daily Climate Risk Score
df["daily_climate_risk_score"] = (
    df["heat_risk_day"] * 40
    + df["heavy_rain_day"] * 30
    + df["dry_day"] * 10
    + df["very_hot_day"] * 20
)

df["daily_climate_risk_score"] = df["daily_climate_risk_score"].clip(upper=100)
df[[
    "date",
    "city",
    "heat_risk_day",
    "heavy_rain_day",
    "dry_day",
    "very_hot_day",
    "daily_climate_risk_score",
]].head()

,date,city,heat_risk_day,heavy_rain_day,dry_day,very_hot_day,daily_climate_risk_score
0,2020-01-01,Mandalay,0,0,0,0,0
1,2020-01-02,Mandalay,0,0,1,0,10
2,2020-01-03,Mandalay,0,0,0,0,0
3,2020-01-04,Mandalay,0,0,0,0,0
4,2020-01-05,Mandalay,0,0,0,0,0

In [25]:
# Create Risk level
def assign_risk_level(score):
    if score <= 30:
        return "Low"
    elif score <= 60:
        return "Moderate"
    else:
        return "High"

df["risk_level"] = df["daily_climate_risk_score"].apply(assign_risk_level)
df[["date", "city", "daily_climate_risk_score", "risk_level"]].head()

        date      city  daily_climate_risk_score risk_level
0 2020-01-01  Mandalay                         0        Low
1 2020-01-02  Mandalay                        10        Low
2 2020-01-03  Mandalay                         0        Low
3 2020-01-04  Mandalay                         0        Low
4 2020-01-05  Mandalay                         0        Low

In [26]:
## Final Dataset Validation
print("Final dataset shape:", df.shape)
print("Final columns:")
print(df.columns.tolist())

Final dataset shape: (8768, 27)
Final columns:
['date', 'temperature_avg', 'temperature_max', 'temperature_min', 'rainfall', 'humidity', 'wind_speed', 'solar_radiation', 'city', 'country', 'latitude', 'longitude', 'year', 'month', 'month_name', 'day', 'day_of_year', 'season', 'heat_risk_day', 'very_hot_day', 'heavy_rain_day', 'dry_day', 'temperature_range', 'rainfall_category', 'temperature_category', 'daily_climate_risk_score', 'risk_level']

In [27]:
df.isnull().sum()

date                        0
temperature_avg             0
temperature_max             0
temperature_min             0
rainfall                    0
humidity                    0
wind_speed                  0
solar_radiation             0
city                        0
country                     0
latitude                    0
longitude                   0
year                        0
month                       0
month_name                  0
day                         0
day_of_year                 0
season                      0
heat_risk_day               0
very_hot_day                0
heavy_rain_day              0
dry_day                     0
temperature_range           0
rainfall_category           0
temperature_category        0
daily_climate_risk_score    0
risk_level                  0
dtype: int64

In [28]:
df.describe()

,date,temperature_avg,temperature_max,temperature_min,rainfall,humidity,wind_speed,solar_radiation,latitude,longitude,year,month,day,day_of_year,heat_risk_day,very_hot_day,heavy_rain_day,dry_day,temperature_range,daily_climate_risk_score
count,8768,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000
mean,2022-12-31 12:00:00,27.265981,32.306771,23.024778,5.678112,68.716178,2.779893,17.574252,14.978775,98.040225,2022.499544,6.521898,15.732664,183.166971,0.223996,0.088504,0.016195,0.484603,9.281994,16.061816
min,2020-01-01 00:00:00,17.570000,23.880000,9.780000,0.000000,16.910000,0.500000,1.470000,1.352100,96.078500,2020.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.260000,0.000000
25%,2021-07-01 18:00:00,26.080000,29.770000,21.717500,0.000000,53.460000,2.100000,15.287500,12.968700,96.086450,2021.000000,4.000000,8.000000,92.000000,0.000000,0.000000,0.000000,0.000000,4.900000,0.000000
50%,2022-12-31 12:00:00,27.280000,31.250000,24.170000,1.150000,75.110000,2.620000,18.040000,18.302100,96.131300,2022.500000,7.000000,16.000000,183.000000,0.000000,0.000000,0.000000,0.000000,8.875000,10.000000
75%,2024-07-01 06:00:00,28.590000,34.490000,25.440000,5.842500,85.262500,3.290000,20.480000,20.312175,98.085075,2024.000000,10.000000,23.000000,274.250000,0.000000,0.000000,0.000000,1.000000,13.330000,10.000000
max,2025-12-31 00:00:00,35.600000,43.920000,30.250000,259.030000,95.200000,8.680000,28.050000,21.958800,103.819800,2025.000000,12.000000,31.000000,366.000000,1.000000,1.000000,1.000000,1.000000,21.060000,70.000000
std,NaN,2.584349,3.464191,3.435344,13.448578,19.223559,0.967781,4.296885,8.074589,3.337233,1.708279,3.449183,8.801872,105.468796,0.416943,0.284042,0.126233,0.499791,4.673445,22.614333

In [29]:
## Check Risk Feature Distribution
risk_distribution = df["risk_level"].value_counts()
risk_distribution

risk_level
Low         6804
Moderate    1278
High         686
Name: count, dtype: int64

In [30]:
# Check City-level Summary
city_summary = df.groupby("city").agg(
    avg_temperature=("temperature_avg", "mean"),
    max_temperature=("temperature_max", "max"),
    total_rainfall=("rainfall","sum"),
    heat_risk_days=("heat_risk_day","sum"),
    very_hot_days=("very_hot_day","sum"),
    heavy_rain_days=("heavy_rain_day","sum"),
    dry_days=("dry_day","sum"),
    avg_risk_score=("daily_climate_risk_score", "mean")
).reset_index()
city_summary

,city,avg_temperature,max_temperature,total_rainfall,heat_risk_days,very_hot_days,heavy_rain_days,dry_days,avg_risk_score
0,Mandalay,27.654407,42.31,2609.82,980,278,0,1432,26.952555
1,Naypyidaw,26.268193,41.90,5579.59,418,153,5,1440,15.661496
2,Singapore,27.359758,34.05,29080.66,0,0,114,220,2.563869
3,Yangon,27.781565,43.92,12515.62,566,345,23,1157,19.069343

In [33]:
# Save the processsed dataset
import os
processed_folder ="../data/processed"
os.makedirs(processed_folder, exist_ok=True)

processed_file_path = "../data/processed/climate_weather_processed.csv"

df.to_csv(processed_file_path, index=False)

print("Processed dataset saved successfully!")
print("File Path:", processed_file_path)

Processed dataset saved successfully!
File Path: ../data/processed/climate_weather_processed.csv

## Notebook Summary

In this notebook, we prepared the raw NASA POWER daily weather dataset for climate risk analysis.

Completed tasks:

- Loaded the raw weather dataset
- Checked missing values and duplicates
- Converted the date column into datetime format
- Created time-based features
- Created seasonal labels
- Created climate risk indicator columns
- Created rainfall and temperature categories
- Created a simple daily climate risk score
- Assigned risk levels
- Saved the processed dataset

The processed dataset is now ready for exploratory data analysis and dashboard development.